/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Delsarte.Code.Linear
import Delsarte.Certificate.Golay
import Delsarte.Certificate.Table1

/-!
# Three codes, three equalities

`Delsarte/Code/Linear.lean` turns a passing minimum-weight check into
`2 ^ k ≤ A n 2 d`. Three upper bounds already proved by Delsarte certificates
are met exactly by a binary linear code, so each becomes an equality:

* `A 23 2 7 = 4096`, the binary Golay code `[23,12,7]`;
* `A 24 2 8 = 4096`, the extended Golay code `[24,12,8]`;
* `A 8 2 4 = 16`, the extended Hamming code `[8,4,4]`.

These are the repository's first equalities on the Hamming side. Until now
every statement about `A n q d` was a bound from above with nothing to meet it.

## Where the generator matrices come from

The Golay code is *cyclic*: it is generated by
`g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1`, one of the two degree-11
factors of `x^23 - 1` over `GF(2)`, and its twelve generator rows are the shifts
`g, x g, …, x^11 g`. So `golayRow` reads a single polynomial rather than
restating a 12×23 table that nobody could check by eye.

The extension to length 24 appends an overall parity bit. Every generator row is
a shift of `g`, which has weight 7 — odd — so every row gets the parity bit `1`,
and `golay24Row` says exactly that.

Only `ham8Row` is written out in full: at 4×8 the matrix *is* the shortest
honest description.

## The controls

A construction file that only ever succeeds proves nothing about its own
checker. Two rejections and two witnesses are recorded:

* flipping one bit of the first Golay generator row drops the minimum weight to
  6, and the check reports `false`. The witness is named rather than left to the
  enumeration: the message `1` — the perturbed row itself — weighs 6;
* the `[8,4,4]` code fails the check at `d = 5`, which it must, since its
  minimum distance is exactly 4;
* the zero message encodes to the zero word. The enumeration skips it by an
  explicit `m == 0` guard, and `cwt_golay_zero` shows what that guard is hiding
  — a word of weight 0, which would defeat any positive `d`.

## What this file costs

Roughly eight and a half minutes of elaboration, almost all of it in
`minWtCheck_golay` and `minWtCheck_golay24`: two enumerations of 4096 codewords,
each evaluated twice — once by the elaborator, once by the kernel.

That is about four times the cost of the standalone probe that chose the
representation, and the reason is visible in `cbit`: it recomputes `row i j` for
every coordinate of every codeword, so `golayGen` is evaluated 276 times per
word instead of the 12 it would take to build the word once as a list. Fixing it
means carrying the codeword as a `List Bool` and re-proving `cbit_xor` through
`List.zipWith`, which is a real amount of work for a build-time saving. Recorded
here so the trade is visible rather than forgotten.
-/

namespace Delsarte

open Finset

set_option maxRecDepth 100000

/-! ### The binary Golay code `[23,12,7]` -/

/-- The coefficients of `g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1`, low
degree first. -/
def golayGen : ℕ → Bool
  | 0 => true | 2 => true | 4 => true | 5 => true | 6 => true
  | 10 => true | 11 => true
  | _ => false

/-- Generator row `i` of the Golay code: the coefficients of `x^i g(x)`. -/
def golayRow (i j : ℕ) : Bool := if i ≤ j then golayGen (j - i) else false

set_option maxHeartbeats 2000000 in
-- Enumerating the 4096 codewords and weighing each costs well over the default
-- budget. Scoped here and to the one other check that needs it.
/-- **The minimum weight of the Golay code is at least 7.** 4095 nonzero
messages weighed in the kernel. -/
theorem minWtCheck_golay : minWtCheck golayRow 12 23 7 = true := by decide

theorem A_twentyThree_two_seven_ge_4096 : 4096 ≤ A 23 2 7 := by
  have h := two_pow_le_A (row := golayRow) (k := 12) (n := 23) (d := 7)
    (by norm_num) minWtCheck_golay
  norm_num at h
  exact h

/-- **`A(23, 2, 7) = 4096`.** The Delsarte certificate bounds it above, the Golay
code meets the bound. -/
theorem A_twentyThree_two_seven_eq_4096 : A 23 2 7 = 4096 :=
  le_antisymm Certificate.A_twentyThree_two_seven_le_4096 A_twentyThree_two_seven_ge_4096

/-! ### The extended Golay code `[24,12,8]` -/

/-- Generator row `i` of the extended Golay code: row `i` of the Golay code
followed by its parity bit, which is `1` because `g` has odd weight 7. -/
def golay24Row (i j : ℕ) : Bool := if j = 23 then true else golayRow i j

set_option maxHeartbeats 2000000 in
-- Same enumeration as `minWtCheck_golay`, one coordinate wider.
theorem minWtCheck_golay24 : minWtCheck golay24Row 12 24 8 = true := by decide

theorem A_24_2_8_ge : 4096 ≤ A 24 2 8 := by
  have h := two_pow_le_A (row := golay24Row) (k := 12) (n := 24) (d := 8)
    (by norm_num) minWtCheck_golay24
  norm_num at h
  exact h

/-- **`A(24, 2, 8) = 4096`.** -/
theorem A_24_2_8_eq : A 24 2 8 = 4096 :=
  le_antisymm Certificate.A_24_2_8_le A_24_2_8_ge

/-! ### The extended Hamming code `[8,4,4]` -/

/-- The generator matrix of the extended Hamming code, in systematic form
`[I₄ | P]`. Small enough that writing it out is the clearest description. -/
def ham8Gen : List (List Bool) :=
  [[true, false, false, false, false, true, true, true],
   [false, true, false, false, true, false, true, true],
   [false, false, true, false, true, true, false, true],
   [false, false, false, true, true, true, true, false]]

def ham8Row (i j : ℕ) : Bool := (ham8Gen.getD i []).getD j false

theorem minWtCheck_ham8 : minWtCheck ham8Row 4 8 4 = true := by decide

theorem A_8_2_4_ge : 16 ≤ A 8 2 4 := by
  have h := two_pow_le_A (row := ham8Row) (k := 4) (n := 8) (d := 4)
    (by norm_num) minWtCheck_ham8
  norm_num at h
  exact h

/-- **`A(8, 2, 4) = 16`.** -/
theorem A_8_2_4_eq : A 8 2 4 = 16 :=
  le_antisymm Certificate.A_8_2_4_le A_8_2_4_ge

/-! ### Controls

The checker has to be able to say no.
-/

/-- One bit flipped in the first generator row. -/
def golayRowPerturbed (i j : ℕ) : Bool :=
  if i = 0 ∧ j = 0 then !golayRow 0 0 else golayRow i j

/-- **The checker rejects the perturbation.** Flipping a single generator bit
produces a codeword of weight 6, so the `d = 7` check fails. A checker that
accepted this would certify nothing. -/
theorem not_minWtCheck_golayPerturbed : minWtCheck golayRowPerturbed 12 23 7 = false := by
  decide

/-- The rejection above is caused by a named codeword, not by an accident of the
enumeration: the message `1` — the perturbed first generator row itself — has
weight 6. Stating the witness costs one codeword instead of 4095. -/
theorem cwt_golayPerturbed_one : cwt golayRowPerturbed 12 23 1 = 6 := by decide

/-- **The `[8,4,4]` code has minimum distance exactly 4**, so the check at
`d = 5` must fail. -/
theorem not_minWtCheck_ham8_five : minWtCheck ham8Row 4 8 5 = false := by decide

/-- What the `m == 0` guard hides: the zero message encodes to the zero word,
which would defeat every positive `d`. Excluding it is the one step of the
enumeration that is not a computation, so it is stated. -/
theorem cwt_golay_zero : cwt golayRow 12 23 0 = 0 := by decide

end Delsarte
