/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Delsarte.Code.Linear
import Delsarte.Certificate.Golay
import Delsarte.Certificate.Table1

/-!
# Three codes, three equalities

`Delsarte/Code/Linear.lean` turns a passing minimum-weight check into
`2 ^ k ≤ A n 2 d`. Three upper bounds already proved by Delsarte certificates
are met exactly by a binary linear code, so each becomes an equality:

* `A 23 2 7 = 4096`, the binary Golay code `[23,12,7]`;
* `A 24 2 8 = 4096`, the extended Golay code `[24,12,8]`;
* `A 8 2 4 = 16`, the extended Hamming code `[8,4,4]`.

These are the repository's first equalities on the Hamming side. Until now
every statement about `A n q d` was a bound from above with nothing to meet it.

## Where the generator matrices come from

The Golay code is *cyclic*: it is generated by
`g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1`, one of the two degree-11
factors of `x^23 - 1` over `GF(2)`, and its twelve generator rows are the shifts
`g, x g, …, x^11 g`. So `golayRow` reads a single polynomial rather than
restating a 12×23 table that nobody could check by eye.

The extension to length 24 appends an overall parity bit. Every generator row is
a shift of `g`, which has weight 7 — odd — so every row gets the parity bit `1`,
and `golay24Row` says exactly that.

Only `ham8Row` is written out in full: at 4×8 the matrix *is* the shortest
honest description.

## The controls

A construction file that only ever succeeds proves nothing about its own
checker. Two rejections and two witnesses are recorded:

* flipping one bit of the first Golay generator row drops the minimum weight to
  6, and the check reports `false`. The witness is named rather than left to the
  enumeration: the message `1` — the perturbed row itself — weighs 6;
* the `[8,4,4]` code fails the check at `d = 5`, which it must, since its
  minimum distance is exactly 4;
* the zero message encodes to the zero word. The enumeration skips it by an
  explicit `m == 0` guard, and `cwt_golay_zero` shows what that guard is hiding
  — a word of weight 0, which would defeat any positive `d`.

## What this file costs, and what that cost taught

The first version compiled here in 8m40 and was **killed on the CI runner** at
just under fifteen minutes. A proof that only builds on the author's machine is
not a result, so the cost had to come down. Three changes did it, and each is
worth recording because none of them touches a single proof.

1. *Generator rows as one numeral.* `golayGen` was a `match` on seven literals;
   it is now the numeral 3189 read with `Nat.testBit`. The kernel special-cases
   shifts and bit tests, a `match` on literals it does not. 8m40 → 4m27.
2. *`decide +kernel`.* Plain `decide` evaluates twice, once in the elaborator and
   once in the kernel. Only the kernel's verdict is trusted, so the elaborator's
   pass is pure waste here.
3. *Splitting the enumeration.* This was the one that mattered. The kernel caches
   every weak-head normal form it computes and never prunes that cache inside a
   declaration, so a single `decide` over 4096 codewords peaked at **22.9 GB** —
   on a runner with 16. Eight declarations of 512 messages compute exactly the
   same thing and peak at 6.4 GB. 3m48 in total.

What remains inefficient is visible in `cbit`: it recomputes `row i j` for every
coordinate of every codeword, so a row is read 23 times per word instead of
once. Removing that means carrying codewords as `List Bool` and re-proving
`cbit_xor` through `List.zipWith` — real work for a build-time saving, not taken.
Recorded so the trade stays visible rather than forgotten.
-/

namespace Delsarte

open Finset

set_option maxRecDepth 100000

/-! ### The binary Golay code `[23,12,7]` -/

/-- `g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1` packed into one numeral:
bit `j` is the coefficient of `x^j`. `3189 = 1 + 4 + 16 + 32 + 64 + 1024 + 2048`.

Written this way rather than as a `match` on seven literals for a reason that is
purely about cost: the kernel special-cases `Nat.shiftLeft` and `Nat.testBit`,
so a row entry is three accelerated operations instead of a chain of equality
tests. At 4096 codewords times 12 rows times 23 coordinates that difference
decides whether the file builds on a CI runner. -/
def golayGen : ℕ := 3189

/-- Generator row `i` of the Golay code: the coefficients of `x^i g(x)`. The
shift also supplies the `j < i` guard for free — the low bits of a shifted
numeral are zero. -/
def golayRow (i j : ℕ) : Bool := (golayGen <<< i).testBit j

/-! **The minimum weight of the Golay code is at least 7**, in eight slices of
512 messages. Each slice carries its own `maxHeartbeats`: the work is far past
the default budget, and splitting it is what keeps the peak memory survivable. -/

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golayChunk0 : minWtCheckFrom golayRow 12 23 7 0 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golayChunk1 : minWtCheckFrom golayRow 12 23 7 512 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golayChunk2 : minWtCheckFrom golayRow 12 23 7 1024 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golayChunk3 : minWtCheckFrom golayRow 12 23 7 1536 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golayChunk4 : minWtCheckFrom golayRow 12 23 7 2048 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golayChunk5 : minWtCheckFrom golayRow 12 23 7 2560 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golayChunk6 : minWtCheckFrom golayRow 12 23 7 3072 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golayChunk7 : minWtCheckFrom golayRow 12 23 7 3584 512 = true := by decide +kernel

/-- The eight chunks, reassembled. -/
theorem minWt_golay : MinWt golayRow 12 23 7 := by
  intro m hm hm0
  rw [show (2 : ℕ) ^ 12 = 4096 from by norm_num] at hm
  rcases lt_or_ge m 512 with h0 | h0
  · exact minWtFrom_of_check golayChunk0 m (Nat.zero_le _) (by omega) hm0
  rcases lt_or_ge m 1024 with h1 | h1
  · exact minWtFrom_of_check golayChunk1 m h0 (by omega) hm0
  rcases lt_or_ge m 1536 with h2 | h2
  · exact minWtFrom_of_check golayChunk2 m h1 (by omega) hm0
  rcases lt_or_ge m 2048 with h3 | h3
  · exact minWtFrom_of_check golayChunk3 m h2 (by omega) hm0
  rcases lt_or_ge m 2560 with h4 | h4
  · exact minWtFrom_of_check golayChunk4 m h3 (by omega) hm0
  rcases lt_or_ge m 3072 with h5 | h5
  · exact minWtFrom_of_check golayChunk5 m h4 (by omega) hm0
  rcases lt_or_ge m 3584 with h6 | h6
  · exact minWtFrom_of_check golayChunk6 m h5 (by omega) hm0
  exact minWtFrom_of_check golayChunk7 m h6 (by omega) hm0

theorem A_twentyThree_two_seven_ge_4096 : 4096 ≤ A 23 2 7 := by
  have h := two_pow_le_A (row := golayRow) (k := 12) (n := 23) (d := 7)
    (by norm_num) minWt_golay
  norm_num at h
  exact h

/-- **`A(23, 2, 7) = 4096`.** The Delsarte certificate bounds it above, the Golay
code meets the bound. -/
theorem A_twentyThree_two_seven_eq_4096 : A 23 2 7 = 4096 :=
  le_antisymm Certificate.A_twentyThree_two_seven_le_4096 A_twentyThree_two_seven_ge_4096

/-! ### The extended Golay code `[24,12,8]` -/

/-- Generator row `i` of the extended Golay code: row `i` of the Golay code
followed by its parity bit, which is `1` because `g` has odd weight 7. -/
def golay24Row (i j : ℕ) : Bool := ((golayGen <<< i) ||| (1 <<< 23)).testBit j

/-! The same enumeration, one coordinate wider. -/

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Chunk0 : minWtCheckFrom golay24Row 12 24 8 0 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Chunk1 : minWtCheckFrom golay24Row 12 24 8 512 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Chunk2 : minWtCheckFrom golay24Row 12 24 8 1024 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Chunk3 : minWtCheckFrom golay24Row 12 24 8 1536 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Chunk4 : minWtCheckFrom golay24Row 12 24 8 2048 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Chunk5 : minWtCheckFrom golay24Row 12 24 8 2560 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Chunk6 : minWtCheckFrom golay24Row 12 24 8 3072 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Chunk7 : minWtCheckFrom golay24Row 12 24 8 3584 512 = true := by decide +kernel

/-- The eight chunks, reassembled. -/
theorem minWt_golay24 : MinWt golay24Row 12 24 8 := by
  intro m hm hm0
  rw [show (2 : ℕ) ^ 12 = 4096 from by norm_num] at hm
  rcases lt_or_ge m 512 with h0 | h0
  · exact minWtFrom_of_check golay24Chunk0 m (Nat.zero_le _) (by omega) hm0
  rcases lt_or_ge m 1024 with h1 | h1
  · exact minWtFrom_of_check golay24Chunk1 m h0 (by omega) hm0
  rcases lt_or_ge m 1536 with h2 | h2
  · exact minWtFrom_of_check golay24Chunk2 m h1 (by omega) hm0
  rcases lt_or_ge m 2048 with h3 | h3
  · exact minWtFrom_of_check golay24Chunk3 m h2 (by omega) hm0
  rcases lt_or_ge m 2560 with h4 | h4
  · exact minWtFrom_of_check golay24Chunk4 m h3 (by omega) hm0
  rcases lt_or_ge m 3072 with h5 | h5
  · exact minWtFrom_of_check golay24Chunk5 m h4 (by omega) hm0
  rcases lt_or_ge m 3584 with h6 | h6
  · exact minWtFrom_of_check golay24Chunk6 m h5 (by omega) hm0
  exact minWtFrom_of_check golay24Chunk7 m h6 (by omega) hm0

theorem A_24_2_8_ge : 4096 ≤ A 24 2 8 := by
  have h := two_pow_le_A (row := golay24Row) (k := 12) (n := 24) (d := 8)
    (by norm_num) minWt_golay24
  norm_num at h
  exact h

/-- **`A(24, 2, 8) = 4096`.** -/
theorem A_24_2_8_eq : A 24 2 8 = 4096 :=
  le_antisymm Certificate.A_24_2_8_le A_24_2_8_ge

/-! ### The extended Hamming code `[8,4,4]` -/

/-- The generator matrix of the extended Hamming code, in systematic form
`[I₄ | P]`. Small enough that writing it out is the clearest description. -/
def ham8Gen : List (List Bool) :=
  [[true, false, false, false, false, true, true, true],
   [false, true, false, false, true, false, true, true],
   [false, false, true, false, true, true, false, true],
   [false, false, false, true, true, true, true, false]]

def ham8Row (i j : ℕ) : Bool := (ham8Gen.getD i []).getD j false

theorem minWtCheck_ham8 : minWtCheck ham8Row 4 8 4 = true := by decide +kernel

theorem A_8_2_4_ge : 16 ≤ A 8 2 4 := by
  have h := two_pow_le_A (row := ham8Row) (k := 4) (n := 8) (d := 4)
    (by norm_num) (minWt_of_check minWtCheck_ham8)
  norm_num at h
  exact h

/-- **`A(8, 2, 4) = 16`.** -/
theorem A_8_2_4_eq : A 8 2 4 = 16 :=
  le_antisymm Certificate.A_8_2_4_le A_8_2_4_ge

/-! ### Controls

The checker has to be able to say no.
-/

/-- One bit flipped in the first generator row. -/
def golayRowPerturbed (i j : ℕ) : Bool :=
  if i = 0 ∧ j = 0 then !golayRow 0 0 else golayRow i j

/-- **The checker rejects the perturbation.** Flipping a single generator bit
produces a codeword of weight 6, so the `d = 7` check fails. A checker that
accepted this would certify nothing. -/
theorem not_minWtCheck_golayPerturbed : minWtCheck golayRowPerturbed 12 23 7 = false := by
  decide +kernel

/-- The rejection above is caused by a named codeword, not by an accident of the
enumeration: the message `1` — the perturbed first generator row itself — has
weight 6. Stating the witness costs one codeword instead of 4095. -/
theorem cwt_golayPerturbed_one : cwt golayRowPerturbed 12 23 1 = 6 := by decide +kernel

/-- **The `[8,4,4]` code has minimum distance exactly 4**, so the check at
`d = 5` must fail. -/
theorem not_minWtCheck_ham8_five : minWtCheck ham8Row 4 8 5 = false := by decide +kernel

/-- What the `m == 0` guard hides: the zero message encodes to the zero word,
which would defeat every positive `d`. Excluding it is the one step of the
enumeration that is not a computation, so it is stated. -/
theorem cwt_golay_zero : cwt golayRow 12 23 0 = 0 := by decide +kernel

/-! ## Every Golay weight is a multiple of four

The extended binary Golay code is *doubly even*: the weight enumerator is
`1 + 759 x^8 + 2576 x^12 + 759 x^16 + x^24`, so no weight escapes `4 ℕ`. The
fact is textbook, the check here is not: it is the same enumeration over the
4096 messages that `minWt_golay24` runs, split the same way and for the same
reason.

What it buys, through `cinter_even`, is that any two Golay codewords meet in an
even number of coordinates. That parity is what separates the second and third
Leech families in `Delsarte/Lattice/Separation.lean`; the minimum distance
alone leaves a gap there.
-/

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Dvd0 : wtDvdCheckFrom golay24Row 12 24 4 0 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Dvd1 : wtDvdCheckFrom golay24Row 12 24 4 512 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Dvd2 : wtDvdCheckFrom golay24Row 12 24 4 1024 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Dvd3 : wtDvdCheckFrom golay24Row 12 24 4 1536 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Dvd4 : wtDvdCheckFrom golay24Row 12 24 4 2048 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Dvd5 : wtDvdCheckFrom golay24Row 12 24 4 2560 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Dvd6 : wtDvdCheckFrom golay24Row 12 24 4 3072 512 = true := by decide +kernel

set_option maxHeartbeats 2000000 in
-- One slice of the enumeration: 512 codewords, far past the default budget.
theorem golay24Dvd7 : wtDvdCheckFrom golay24Row 12 24 4 3584 512 = true := by decide +kernel

/-- The eight blocks, reassembled. -/
theorem wtDvd_golay24 : ∀ m < 4096, cwt golay24Row 12 24 m % 4 = 0 := by
  intro m hm
  rcases lt_or_ge m 512 with h0 | h0
  · exact wtDvdFrom_of_check golay24Dvd0 m (Nat.zero_le _) (by omega)
  rcases lt_or_ge m 1024 with h1 | h1
  · exact wtDvdFrom_of_check golay24Dvd1 m h0 (by omega)
  rcases lt_or_ge m 1536 with h2 | h2
  · exact wtDvdFrom_of_check golay24Dvd2 m h1 (by omega)
  rcases lt_or_ge m 2048 with h3 | h3
  · exact wtDvdFrom_of_check golay24Dvd3 m h2 (by omega)
  rcases lt_or_ge m 2560 with h4 | h4
  · exact wtDvdFrom_of_check golay24Dvd4 m h3 (by omega)
  rcases lt_or_ge m 3072 with h5 | h5
  · exact wtDvdFrom_of_check golay24Dvd5 m h4 (by omega)
  rcases lt_or_ge m 3584 with h6 | h6
  · exact wtDvdFrom_of_check golay24Dvd6 m h5 (by omega)
  exact wtDvdFrom_of_check golay24Dvd7 m h6 (by omega)

/-- Two Golay codewords meet in an even number of coordinates. -/
theorem cinter_golay24_even {a b : ℕ} (ha : a < 4096) (hb : b < 4096) :
    cinter golay24Row 12 24 a b % 2 = 0 := by
  have h12 : (2 : ℕ) ^ 12 = 4096 := by norm_num
  have ha' : a < 2 ^ 12 := by rw [h12]; exact ha
  have hb' : b < 2 ^ 12 := by rw [h12]; exact hb
  have hx : a ^^^ b < 4096 := by rw [← h12]; exact xor_lt_two_pow ha' hb'
  exact cinter_even (wtDvd_golay24 a ha) (wtDvd_golay24 b hb) (wtDvd_golay24 _ hx)

/-! ### Negative control

Double evenness is a property of the *extended* code, not of the Golay code it
extends. The 23-coordinate version has codewords of weight 7, so the very same
check fails on its first block. A check that passes everywhere it is pointed
proves nothing. -/
theorem not_wtDvdCheck_golay23 : wtDvdCheckFrom golayRow 12 23 4 0 512 = false := by
  decide +kernel

end Delsarte
