/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Delsarte.Code.Basic

/-!
# Binary linear codes, and the first equalities `A n 2 d = B`

Every bound in `Delsarte/Certificate/` reads `A n q d ≤ B`. None of them
constructs a code, so none of them can be sharpened to an equality. This file
supplies the missing half for three of them.

## Why linearity, and not a direct check

`MinDistAtLeast` quantifies over pairs. For the Golay code that is `4096^2`,
close to 17 million Hamming distances — out of reach of the kernel, which spent
110 seconds on the 28 680 dot products of `Delsarte/Sphere/E8.lean`.

A *linear* code collapses the pair condition to a single-word one: `d(x,y)` is
the weight of `x + y`, and `x + y` is again a codeword. So 4095 weights replace
17 million distances, four orders of magnitude.

## The representation was measured, not chosen

Three encodings of "the codeword of message `m`" were timed on the Golay code
before one was kept.

| messages indexed by | arithmetic | kernel cost           |
| ------------------- | ---------- | --------------------- |
| `Fin 12 → ZMod 2`   | `ZMod 2`   | killed by OOM, 12m42s |
| `ℕ`, read bitwise   | `Bool`     | **1m16s**             |
| `ℕ`, read bitwise   | `ZMod 2`   | 8m45s                 |

The first is by far the cleanest algebraically — additivity of the encoding is
`add_mul` followed by `Finset.sum_add_distrib`, with no lemma about bits — and
it is the one that does not run: enumerating a function type builds 4096
closures and exhausts memory. The third computes, seven times slower.

So the middle row is what this file implements, and the price is paid in
`cbit_xor`: additivity has to be proved by hand, coordinate by coordinate, from
`Nat.testBit_xor` and an induction on a `Bool.xor` fold.

## What the enumeration gives for free

As in `E8.lean`, injectivity is not an assumption. If two messages had the same
codeword their difference would be a codeword of weight zero, hence of weight
below `d`; the minimum-weight computation already excludes that. The cardinality
`2 ^ k` is a consequence of the same `decide`, not a separate claim.

## The generator matrices are described, not tabulated

The Golay code here is the cyclic code generated by
`g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1`, and its twelve rows are the
shifts of `g`. The mathematical object is the polynomial; a pasted 12×23 table
would be an unauditable restatement of it.

## What is not here, and why

* `A 32 2 4 ≤ 2^26` is met by the extended Hamming code `[32,26,4]`, but that
  means enumerating 67 million codewords.
* `A 16 2 6 ≤ 256` is met by the Nordstrom–Robinson code, which is **not
  linear**. The minimum-weight argument has no purchase on it.
* `A 10 2 5 ≤ 12`, `A 11 2 5 ≤ 24` and `A 12 2 6 ≤ 24` have optima that are not
  powers of two, so no binary linear code attains them.
* `A 12 2 5 ≤ 40` is not tight (the true value is 32). There is nothing to meet.
-/

namespace Delsarte

open Finset

/-! ### Messages, codewords, weights -/

/-- The `j`-th bit of the codeword encoding the message `m`: the parity of the
generator rows selected by the bits of `m`. Only the first `k` bits of `m` are
read, so the encoding is blind to anything above the dimension. -/
def cbit (row : ℕ → ℕ → Bool) (k m j : ℕ) : Bool :=
  (List.range k).foldl (fun acc i => Bool.xor acc (m.testBit i && row i j)) false

/-- The Hamming weight of the codeword encoding `m`, counted over `List.range n`
rather than over `Fin n`: this is the form the kernel evaluates cheaply. -/
def cwt (row : ℕ → ℕ → Bool) (k n m : ℕ) : ℕ :=
  (List.range n).countP (cbit row k m)

/-- The codeword of the message `m`, as a word of `Delsarte.Code`. -/
def cword (row : ℕ → ℕ → Bool) (k n : ℕ) (m : ℕ) : Word n 2 :=
  fun j => if cbit row k m (j : ℕ) then 1 else 0

/-- The code generated by the first `k` rows of `row`. -/
def linCode (row : ℕ → ℕ → Bool) (k n : ℕ) : Code n 2 :=
  (Finset.range (2 ^ k)).image (cword row k n)

/-! ### Additivity of the encoding

The one place where the cheap representation costs something. Everything below
rests on `cbit_xor`.
-/

/-- An accumulator can be pulled out of a `Bool.xor` fold. -/
theorem foldl_xor_pull (f : ℕ → Bool) :
    ∀ (l : List ℕ) (a : Bool),
      l.foldl (fun acc i => Bool.xor acc (f i)) a
        = Bool.xor a (l.foldl (fun acc i => Bool.xor acc (f i)) false) := by
  intro l
  induction l with
  | nil => intro a; simp
  | cons i t ih =>
      intro a
      simp only [List.foldl_cons]
      rw [ih (Bool.xor a (f i)), ih (Bool.xor false (f i))]
      cases a <;> cases f i <;> simp

/-- A `Bool.xor` fold of a pointwise `Bool.xor` splits. -/
theorem foldl_xor_add (f g : ℕ → Bool) :
    ∀ l : List ℕ,
      l.foldl (fun acc i => Bool.xor acc (Bool.xor (f i) (g i))) false
        = Bool.xor (l.foldl (fun acc i => Bool.xor acc (f i)) false)
            (l.foldl (fun acc i => Bool.xor acc (g i)) false) := by
  intro l
  induction l with
  | nil => simp
  | cons i t ih =>
      simp only [List.foldl_cons, Bool.false_xor]
      rw [foldl_xor_pull _ t, foldl_xor_pull f t, foldl_xor_pull g t, ih]
      cases f i <;> cases g i <;> simp

/-- **The encoding is additive.** Bitwise `xor` on messages becomes coordinatewise
`xor` on codewords. -/
theorem cbit_xor (row : ℕ → ℕ → Bool) (k m m' j : ℕ) :
    cbit row k (m ^^^ m') j = Bool.xor (cbit row k m j) (cbit row k m' j) := by
  have h : ∀ i : ℕ, ((m ^^^ m').testBit i && row i j)
      = Bool.xor (m.testBit i && row i j) (m'.testBit i && row i j) := by
    intro i
    rw [Nat.testBit_xor]
    cases m.testBit i <;> cases m'.testBit i <;> cases row i j <;> rfl
  unfold cbit
  simp only [h]
  exact foldl_xor_add _ _ _

/-! ### Bit arithmetic

Two facts about `xor` that the main argument needs and that are not stated in
the form required upstream.
-/

theorem xor_ne_zero {a b : ℕ} (h : a ≠ b) : a ^^^ b ≠ 0 := by
  intro hz
  apply h
  have hc := congrArg (fun x => x ^^^ b) hz
  simpa [Nat.xor_assoc, Nat.xor_self] using hc

theorem xor_lt_two_pow {a b k : ℕ} (ha : a < 2 ^ k) (hb : b < 2 ^ k) :
    a ^^^ b < 2 ^ k :=
  Nat.bitwise_lt_two_pow ha hb

/-! ### From the list count to the Hamming distance -/

/-- `List.countP` over `range n` is the corresponding `Finset.range` sum. -/
theorem countP_range_eq_sum (p : ℕ → Bool) :
    ∀ n : ℕ, (List.range n).countP p = ∑ j ∈ Finset.range n, if p j then 1 else 0
  | 0 => by simp
  | (n + 1) => by
      rw [List.range_succ, List.countP_append, countP_range_eq_sum p n,
        Finset.sum_range_succ]
      cases h : p n <;> simp [h]

/-- Two codewords differ at `j` exactly where the codeword of the difference is
nonzero. This is `cbit_xor` read through `cword`. -/
theorem cword_ne_iff (row : ℕ → ℕ → Bool) (k n m m' : ℕ) (j : Fin n) :
    cword row k n m j ≠ cword row k n m' j ↔ cbit row k (m ^^^ m') (j : ℕ) = true := by
  rw [cbit_xor]
  unfold cword
  cases cbit row k m (j : ℕ) <;> cases cbit row k m' (j : ℕ) <;> simp

/-- **Distance is weight.** The Hamming distance between two codewords is the
weight of the codeword of the bitwise difference of their messages. -/
theorem hammingDist_cword (row : ℕ → ℕ → Bool) (k n m m' : ℕ) :
    hammingDist (cword row k n m) (cword row k n m') = cwt row k n (m ^^^ m') := by
  rw [hammingDist, cwt, countP_range_eq_sum, Finset.card_filter]
  rw [← Fin.sum_univ_eq_sum_range (fun j => if cbit row k (m ^^^ m') j then 1 else 0) n]
  refine Finset.sum_congr rfl fun j _ => ?_
  by_cases hb : cbit row k (m ^^^ m') (j : ℕ) = true
  · rw [if_pos ((cword_ne_iff row k n m m' j).mpr hb), if_pos hb]
  · rw [if_neg fun hc => hb ((cword_ne_iff row k n m m' j).mp hc), if_neg hb]

/-! ### The packaged statement

One decidable check per code; everything else is generic.
-/

/-- What the constructions below need: every nonzero message under `2 ^ k`
encodes to a codeword of weight at least `d`. -/
def MinWt (row : ℕ → ℕ → Bool) (k n d : ℕ) : Prop :=
  ∀ m < 2 ^ k, m ≠ 0 → d ≤ cwt row k n m

/-- The check the kernel runs, in one piece. -/
def minWtCheck (row : ℕ → ℕ → Bool) (k n d : ℕ) : Bool :=
  (List.range (2 ^ k)).all fun m => m == 0 || decide (d ≤ cwt row k n m)

/-- The same check restricted to the messages `lo, …, lo + len - 1`.

The split exists for one reason, and it is not tidiness. The kernel caches every
weak-head normal form it computes, and the cache is never pruned inside a single
declaration, so one `decide` over the 4096 Golay codewords peaks near 23 GB and
is killed on a CI runner with 16. Each declaration is checked with a fresh
cache, so eight declarations of 512 messages peak at an eighth of that. The
arithmetic done is identical; only the peak differs. -/
def minWtCheckFrom (row : ℕ → ℕ → Bool) (k n d lo len : ℕ) : Bool :=
  (List.range' lo len).all fun m => m == 0 || decide (d ≤ cwt row k n m)

theorem minWt_of_check {row : ℕ → ℕ → Bool} {k n d : ℕ} (h : minWtCheck row k n d = true) :
    MinWt row k n d := by
  intro m hm hm0
  have h1 := List.all_eq_true.mp h m (List.mem_range.mpr hm)
  rcases Bool.or_eq_true _ _ |>.mp h1 with h2 | h2
  · exact absurd (by simpa using h2) hm0
  · exact of_decide_eq_true h2

/-- One chunk of the check, read back as a statement about the messages it
covers. Assembling the chunks is left to the call site, where the arithmetic is
concrete. -/
theorem minWtFrom_of_check {row : ℕ → ℕ → Bool} {k n d lo len : ℕ}
    (h : minWtCheckFrom row k n d lo len = true) :
    ∀ m, lo ≤ m → m < lo + len → m ≠ 0 → d ≤ cwt row k n m := by
  intro m h1 h2 hm0
  have hall := List.all_eq_true.mp h m (List.mem_range'_1.mpr ⟨h1, h2⟩)
  rcases Bool.or_eq_true _ _ |>.mp hall with h3 | h3
  · exact absurd (by simpa using h3) hm0
  · exact of_decide_eq_true h3

/-- The generated code meets the minimum distance the weight check reports. -/
theorem minDistAtLeast_linCode {row : ℕ → ℕ → Bool} {k n d : ℕ} (hw : MinWt row k n d) :
    MinDistAtLeast d (linCode row k n) := by
  rintro x hx y hy hxy
  rw [linCode, Finset.mem_image] at hx hy
  obtain ⟨m, hm, rfl⟩ := hx
  obtain ⟨m', hm', rfl⟩ := hy
  rw [Finset.mem_range] at hm hm'
  have hne : m ≠ m' := by rintro rfl; exact hxy rfl
  rw [hammingDist_cword]
  exact hw _ (xor_lt_two_pow hm hm') (xor_ne_zero hne)

/-- ...and it has exactly `2 ^ k` elements. Injectivity is read off the same
check: equal codewords would force a nonzero message of weight `0 < d`. -/
theorem card_linCode {row : ℕ → ℕ → Bool} {k n d : ℕ} (hd : 0 < d) (hw : MinWt row k n d) :
    (linCode row k n).card = 2 ^ k := by
  rw [linCode, Finset.card_image_of_injOn, Finset.card_range]
  intro m hm m' hm' hmm
  rw [Finset.mem_coe, Finset.mem_range] at hm hm'
  by_contra hne
  have hdist : hammingDist (cword row k n m) (cword row k n m') = 0 := by
    rw [hmm, hammingDist_self]
  rw [hammingDist_cword] at hdist
  have := hw _ (xor_lt_two_pow hm hm') (xor_ne_zero hne)
  omega

/-- **The lower bound.** A weight check that passes hands back `2 ^ k ≤ A n 2 d`. -/
theorem two_pow_le_A {row : ℕ → ℕ → Bool} {k n d : ℕ} (hd : 0 < d) (hw : MinWt row k n d) :
    2 ^ k ≤ A n 2 d := by
  have := card_le_A (minDistAtLeast_linCode hw)
  rwa [card_linCode hd hw] at this

/-! ### Support overlaps, and weights modulo a fixed number

`cbit_xor` says the encoding is additive. Counting where two codewords are both
set turns that into inclusion-exclusion, and inclusion-exclusion turns a
divisibility statement about weights into a parity statement about overlaps.
The Leech separation needs the second form, not the first.
-/

/-- How many coordinates carry a one in both codewords. -/
def cinter (row : ℕ → ℕ → Bool) (k n a b : ℕ) : ℕ :=
  (List.range n).countP fun j => cbit row k a j && cbit row k b j

/-- **Inclusion-exclusion on supports.** Read through `cbit_xor`, so the third
weight really is the weight of a codeword and not of an ambient sum. -/
theorem cwt_add_cwt (row : ℕ → ℕ → Bool) (k n a b : ℕ) :
    cwt row k n a + cwt row k n b = cwt row k n (a ^^^ b) + 2 * cinter row k n a b := by
  simp only [cwt, cinter, countP_range_eq_sum]
  rw [← Finset.sum_add_distrib, Finset.mul_sum, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [cbit_xor]
  cases cbit row k a j <;> cases cbit row k b j <;> simp

/-- Every weight divisible by four forces every overlap even. -/
theorem cinter_even {row : ℕ → ℕ → Bool} {k n a b : ℕ}
    (ha : cwt row k n a % 4 = 0) (hb : cwt row k n b % 4 = 0)
    (hab : cwt row k n (a ^^^ b) % 4 = 0) : cinter row k n a b % 2 = 0 := by
  have h := cwt_add_cwt row k n a b
  omega

/-- What the kernel runs for a divisibility claim, one block of messages at a
time. Same reason for the split as `minWtCheckFrom`: a fresh cache per
declaration keeps the peak memory an eighth of what one pass would take. -/
def wtDvdCheckFrom (row : ℕ → ℕ → Bool) (k n r lo len : ℕ) : Bool :=
  (List.range' lo len).all fun m => cwt row k n m % r == 0

/-- One block of the divisibility check, read back as a statement. -/
theorem wtDvdFrom_of_check {row : ℕ → ℕ → Bool} {k n r lo len : ℕ}
    (h : wtDvdCheckFrom row k n r lo len = true) :
    ∀ m, lo ≤ m → m < lo + len → cwt row k n m % r = 0 := by
  intro m h1 h2
  have hall := List.all_eq_true.mp h m (List.mem_range'_1.mpr ⟨h1, h2⟩)
  simpa using hall

end Delsarte
