/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Mathlib.Algebra.Polynomial.AlgebraMap
import Mathlib.Algebra.Polynomial.Roots
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-!
# Certified nonpositivity on an interval

The Delsarte LP on the sphere asks that a certificate polynomial satisfy
`f t ≤ 0` for every `t` in an interval. That is not a finite computation, so it
needs a certificate of its own.

## The certificate

A rational polynomial `f` is certified nonpositive on `[a, b]` by exhibiting

`-f = σ₀ + (X - a) σ₁ + (b - X) σ₂ + (X - a)(b - X) σ₃`

with every `σ` a sum of squares of rational polynomials — that is, by writing
`-f` in the quadratic module generated by `X - a` and `b - X`.

## Why this and not Sturm

Only **soundness** is ever needed: on `[a, b]` the factors `t - a` and `b - t`
are nonnegative, and so is every square, so the right-hand side is nonnegative
and `f t ≤ 0` follows. That argument is four lines and holds for any supplied
certificate.

The converse — that every polynomial nonpositive on `[a, b]` admits such a
decomposition — is Markov-Lukács, and it never has to be formalized, because the
decomposition is *supplied*, not derived. A Sturm-based verifier would require
formalizing Sturm's theorem itself for exactly the same guarantee. Finding the
`σ` is the solver's job and stays outside the trust base, as the dual vector `y`
does on the Hamming side.

## Proof versus replay

Unlike the dual certificate of `Delsarte.Certificate.Verify`, there is nothing
here for a `Bool` checker to add. The check is a *polynomial identity*, and the
tool that settles polynomial identities in Lean is the kernel itself, via `ring`
or `Polynomial.funext`. A compiled re-execution would be strictly weaker than the
proof that already has to be supplied to build the structure.
-/

namespace Delsarte.Certificate

open Polynomial

/-- The sum of the squares of a list of polynomials. -/
noncomputable def sosPoly (ps : List ℚ[X]) : ℚ[X] := (ps.map fun p => p ^ 2).sum

@[simp]
theorem sosPoly_nil : sosPoly [] = 0 := rfl

@[simp]
theorem sosPoly_cons (p : ℚ[X]) (ps : List ℚ[X]) :
    sosPoly (p :: ps) = p ^ 2 + sosPoly ps := rfl

theorem aeval_sosPoly (t : ℝ) (ps : List ℚ[X]) :
    aeval t (sosPoly ps) = (ps.map fun p => (aeval t p) ^ 2).sum := by
  induction ps with
  | nil => simp
  | cons p ps ih => simp [ih]

/-- A sum of squares evaluates to a nonnegative real. -/
theorem aeval_sosPoly_nonneg (t : ℝ) (ps : List ℚ[X]) : 0 ≤ aeval t (sosPoly ps) := by
  rw [aeval_sosPoly]
  refine List.sum_nonneg fun x hx => ?_
  simp only [List.mem_map] at hx
  obtain ⟨p, _, rfl⟩ := hx
  positivity

/-- A certificate that `f` is nonpositive on `[a, b]`: a decomposition of `-f` in
the quadratic module generated by `X - a` and `b - X`. -/
structure IntervalCert (a b : ℚ) (f : ℚ[X]) where
  /-- The unconstrained sum of squares. -/
  sq : List ℚ[X] := []
  /-- The sum of squares multiplied by `X - a`. -/
  sqA : List ℚ[X] := []
  /-- The sum of squares multiplied by `b - X`. -/
  sqB : List ℚ[X] := []
  /-- The sum of squares multiplied by `(X - a) (b - X)`. -/
  sqAB : List ℚ[X] := []
  /-- The decomposition itself. This is the whole verification. -/
  identity : -f = sosPoly sq + (X - C a) * sosPoly sqA + (C b - X) * sosPoly sqB
    + (X - C a) * (C b - X) * sosPoly sqAB

/-- **Soundness.** A certified polynomial is nonpositive everywhere on the
interval. -/
theorem aeval_nonpos_of_intervalCert {a b : ℚ} {f : ℚ[X]} (cert : IntervalCert a b f)
    {t : ℝ} (ha : (a : ℝ) ≤ t) (hb : t ≤ (b : ℝ)) : aeval t f ≤ 0 := by
  have h := congrArg (aeval t) cert.identity
  simp only [map_add, map_mul, map_sub, map_neg, aeval_X, aeval_C, eq_ratCast] at h
  have h0 := aeval_sosPoly_nonneg t cert.sq
  have hA : 0 ≤ (t - (a : ℝ)) * aeval t (sosPoly cert.sqA) :=
    mul_nonneg (by linarith) (aeval_sosPoly_nonneg t cert.sqA)
  have hB : 0 ≤ ((b : ℝ) - t) * aeval t (sosPoly cert.sqB) :=
    mul_nonneg (by linarith) (aeval_sosPoly_nonneg t cert.sqB)
  have hAB : 0 ≤ (t - (a : ℝ)) * ((b : ℝ) - t) * aeval t (sosPoly cert.sqAB) :=
    mul_nonneg (mul_nonneg (by linarith) (by linarith)) (aeval_sosPoly_nonneg t cert.sqAB)
  linarith

/-! ## Negative control

The multipliers are not decoration. A polynomial that is negative *somewhere* can
never be a bare sum of squares, so a certificate for such a polynomial must use
`X - a` or `b - X`, and is therefore tied to its interval.
-/

/-- A polynomial taking a negative value is not a sum of squares. -/
theorem not_sosPoly_of_aeval_neg {p : ℚ[X]} {t : ℝ} (h : aeval t p < 0) (ps : List ℚ[X]) :
    p ≠ sosPoly ps := by
  intro hp
  have := aeval_sosPoly_nonneg t ps
  rw [← hp] at this
  linarith

end Delsarte.Certificate
