/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Delsarte.Certificate.Integer

/-!
# Certified bounds, part 3 of 3: `A(6,2,3)`, `A(10,2,5)`, `A(12,2,5)`, `A(15,2,6)`

One third of the table described in `Delsarte/Certificate/Table.lean`. The split
is not cosmetic: these three modules import only the verifier, so Lake elaborates
them in parallel.

Each certificate is stored as integers scaled by its common denominator, and each
check is `decide`: the kernel reduces the whole thing in `ℤ`, see
`Delsarte/Certificate/Integer.lean`. The rational form is derived from the integer
one rather than transcribed, so the two cannot drift apart.

Generated by `delsarte_lp.emit_lean`; see `Delsarte/Certificate/Table.lean` for
why these declarations are generated rather than typed.
-/

namespace Delsarte.Certificate

open Delsarte

-- kernel reduction of the Krawtchouk table needs more than the default depth
set_option maxRecDepth 100000

/-- Certificate for `n = 6`, `d = 3`, scaled by its common denominator
`1`. Index `0` is unused. -/
def cert6_3Int : List ℤ :=
  [0, 1, 0, 0, 0, 0, 1]

/-- The common denominator of `cert6_3`. -/
def cert6_3Den : ℤ := 1

/-- The same certificate as rationals: `y 1 = 1`, `y 6 = 1`. Derived from the integer
form, so the two cannot drift apart. -/
def cert6_3 : ℕ → ℚ := ratOfInt cert6_3Int cert6_3Den

-- 4 dual constraints, each a sum of 6 integer products
theorem intCheck_cert6_3 : intCheck 6 3 cert6_3Int cert6_3Den = true := by decide

theorem dualCert_cert6_3 : DualCert 6 2 3 cert6_3 :=
  dualCert_of_intCheck intCheck_cert6_3

theorem A_6_2_3_le : A 6 2 3 ≤ 8 :=
  A_le_of_intCert (p := cert6_3Int) (D := cert6_3Den) (by norm_num) intCheck_cert6_3
    (by decide)



/-- Certificate for `n = 10`, `d = 5`, scaled by its common denominator
`1`. Index `0` is unused. -/
def cert10_5Int : List ℤ :=
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]

/-- The common denominator of `cert10_5`. -/
def cert10_5Den : ℤ := 1

/-- The same certificate as rationals: `y 1 = 1`, `y 10 = 1`. Derived from the integer
form, so the two cannot drift apart. -/
def cert10_5 : ℕ → ℚ := ratOfInt cert10_5Int cert10_5Den

-- 6 dual constraints, each a sum of 10 integer products
theorem intCheck_cert10_5 : intCheck 10 5 cert10_5Int cert10_5Den = true := by decide

theorem dualCert_cert10_5 : DualCert 10 2 5 cert10_5 :=
  dualCert_of_intCheck intCheck_cert10_5

theorem A_10_2_5_le : A 10 2 5 ≤ 12 :=
  A_le_of_intCert (p := cert10_5Int) (D := cert10_5Den) (by norm_num) intCheck_cert10_5
    (by decide)



/-- Certificate for `n = 12`, `d = 5`, scaled by its common denominator
`54`. Index `0` is unused. -/
def cert12_5Int : List ℤ :=
  [0, 36, 14, 3, 0, 0, 0, 0, 0, 0, 0, 5, 30]

/-- The common denominator of `cert12_5`. -/
def cert12_5Den : ℤ := 54

/-- The same certificate as rationals: `y 1 = 2/3`, `y 2 = 7/27`, `y 3 = 1/18`, `y 11 = 5/54`,
`y 12 = 5/9`. Derived from the integer
form, so the two cannot drift apart. -/
def cert12_5 : ℕ → ℚ := ratOfInt cert12_5Int cert12_5Den

-- 8 dual constraints, each a sum of 12 integer products
theorem intCheck_cert12_5 : intCheck 12 5 cert12_5Int cert12_5Den = true := by decide

theorem dualCert_cert12_5 : DualCert 12 2 5 cert12_5 :=
  dualCert_of_intCheck intCheck_cert12_5

theorem A_12_2_5_le : A 12 2 5 ≤ 40 :=
  A_le_of_intCert (p := cert12_5Int) (D := cert12_5Den) (by norm_num) intCheck_cert12_5
    (by decide)



/-- Certificate for `n = 15`, `d = 6`, scaled by its common denominator
`85`. Index `0` is unused. -/
def cert15_6Int : List ℤ :=
  [0, 85, 17, 15, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0]

/-- The common denominator of `cert15_6`. -/
def cert15_6Den : ℤ := 85

/-- The same certificate as rationals: `y 1 = 1`, `y 2 = 1/5`, `y 3 = 3/17`, `y 12 = 2/85`.
Derived from the integer
form, so the two cannot drift apart. -/
def cert15_6 : ℕ → ℚ := ratOfInt cert15_6Int cert15_6Den

-- 10 dual constraints, each a sum of 15 integer products
theorem intCheck_cert15_6 : intCheck 15 6 cert15_6Int cert15_6Den = true := by decide

theorem dualCert_cert15_6 : DualCert 15 2 6 cert15_6 :=
  dualCert_of_intCheck intCheck_cert15_6

theorem A_15_2_6_le : A 15 2 6 ≤ 128 :=
  A_le_of_intCert (p := cert15_6Int) (D := cert15_6Den) (by norm_num) intCheck_cert15_6
    (by decide)
-- The `#`-command linter is off here on purpose: these commands are the replay.
set_option linter.hashCommand false

#guard dualCheck 6 2 3 cert6_3
#guard bound 6 2 cert6_3 == 8
#guard dualCheck 10 2 5 cert10_5
#guard bound 10 2 cert10_5 == 12
#guard dualCheck 12 2 5 cert12_5
#guard bound 12 2 cert12_5 == 40
#guard dualCheck 15 2 6 cert15_6
#guard bound 15 2 cert15_6 == 128

end Delsarte.Certificate
