/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Delsarte.Certificate.Verify

/-!
# Certified bounds, part 1 of 3: `A(8,2,4)`, `A(12,2,6)`, `A(14,2,5)`, `A(24,2,8)`

One third of the table described in `Delsarte/Certificate/Table.lean`. The split
is not cosmetic: these three modules import only the verifier, so Lake elaborates
them in parallel. Exact rational arithmetic is what this repository costs, and
`Delsarte.Certificate.Table` alone was 40 s of a 82 s build.

Generated by `delsarte_lp.emit_lean`; see `Delsarte/Certificate/Table.lean` for
why these declarations are generated rather than typed.
-/

namespace Delsarte.Certificate

open Delsarte

/-- Certificate for `n = 8`, `d = 4`; the linear program's optimum. -/
def cert8_4 : ℕ → ℚ
  | 1 => 1
  | 2 => 1/4
  | _ => 0

set_option maxHeartbeats 800000 in
-- 5 dual constraints, each a sum of 8 Krawtchouk values
theorem dualCert_cert8_4 : DualCert 8 2 4 cert8_4 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert8_4]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 8 2 _ _ (by norm_num)] <;>
      norm_num [cert8_4, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 800000 in
-- the same unfolding, at i = 0
theorem bound_cert8_4 : bound 8 2 cert8_4 = 16 := by
  rw [bound_eq_rec]
  norm_num [cert8_4, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_8_2_4_le : A 8 2 4 ≤ 16 :=
  A_le_of_dualCert (by norm_num) dualCert_cert8_4 (by rw [bound_cert8_4]; norm_num)



/-- Certificate for `n = 12`, `d = 6`; the linear program's optimum. -/
def cert12_6 : ℕ → ℚ
  | 1 => 1
  | 2 => 1/6
  | _ => 0

set_option maxHeartbeats 1200000 in
-- 7 dual constraints, each a sum of 12 Krawtchouk values
theorem dualCert_cert12_6 : DualCert 12 2 6 cert12_6 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert12_6]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 12 2 _ _ (by norm_num)] <;>
      norm_num [cert12_6, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 1200000 in
-- the same unfolding, at i = 0
theorem bound_cert12_6 : bound 12 2 cert12_6 = 24 := by
  rw [bound_eq_rec]
  norm_num [cert12_6, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_12_2_6_le : A 12 2 6 ≤ 24 :=
  A_le_of_dualCert (by norm_num) dualCert_cert12_6 (by rw [bound_cert12_6]; norm_num)



/-- Certificate for `n = 14`, `d = 5`; the linear program's optimum. -/
def cert14_5 : ℕ → ℚ
  | 1 => 1
  | 2 => 1/5
  | 3 => 1/5
  | 12 => 1/5
  | 13 => 1/5
  | 14 => 1
  | _ => 0

set_option maxHeartbeats 1200000 in
-- 10 dual constraints, each a sum of 14 Krawtchouk values
theorem dualCert_cert14_5 : DualCert 14 2 5 cert14_5 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert14_5]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 14 2 _ _ (by norm_num)] <;>
      norm_num [cert14_5, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 1200000 in
-- the same unfolding, at i = 0
theorem bound_cert14_5 : bound 14 2 cert14_5 = 128 := by
  rw [bound_eq_rec]
  norm_num [cert14_5, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_14_2_5_le : A 14 2 5 ≤ 128 :=
  A_le_of_dualCert (by norm_num) dualCert_cert14_5 (by rw [bound_cert14_5]; norm_num)



/-- Certificate for `n = 24`, `d = 8`; the linear program's optimum. -/
def cert24_8 : ℕ → ℚ
  | 1 => 1
  | 2 => 1899761/3371616
  | 3 => 104119/421452
  | 4 => 1466405/17700984
  | 5 => 94789/4425246
  | 6 => 69857/23601312
  | 18 => 47213/23601312
  | 19 => 103097/8850492
  | 20 => 547199/17700984
  | 21 => 12329/210726
  | 22 => 184085/3371616
  | _ => 0

set_option maxHeartbeats 2000000 in
-- 17 dual constraints, each a sum of 24 Krawtchouk values
theorem dualCert_cert24_8 : DualCert 24 2 8 cert24_8 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert24_8]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 24 2 _ _ (by norm_num)] <;>
      norm_num [cert24_8, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 2000000 in
-- the same unfolding, at i = 0
theorem bound_cert24_8 : bound 24 2 cert24_8 = 4096 := by
  rw [bound_eq_rec]
  norm_num [cert24_8, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_24_2_8_le : A 24 2 8 ≤ 4096 :=
  A_le_of_dualCert (by norm_num) dualCert_cert24_8 (by rw [bound_cert24_8]; norm_num)




end Delsarte.Certificate
