/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Delsarte.Certificate.Integer

/-!
# Certified bounds, part 2 of 3: `A(7,2,4)`, `A(11,2,5)`, `A(13,2,3)`, `A(15,2,5)`

One third of the table described in `Delsarte/Certificate/Table.lean`. The split
is not cosmetic: these three modules import only the verifier, so Lake elaborates
them in parallel.

Each certificate is stored as integers scaled by its common denominator, and each
check is `decide`: the kernel reduces the whole thing in `ℤ`, see
`Delsarte/Certificate/Integer.lean`. The rational form is derived from the integer
one rather than transcribed, so the two cannot drift apart.

Generated by `delsarte_lp.emit_lean`; see `Delsarte/Certificate/Table.lean` for
why these declarations are generated rather than typed.
-/

namespace Delsarte.Certificate

open Delsarte

-- kernel reduction of the Krawtchouk table needs more than the default depth
set_option maxRecDepth 100000

/-- Certificate for `n = 7`, `d = 4`, scaled by its common denominator
`1`. Index `0` is unused. -/
def cert7_4Int : List ℤ :=
  [0, 1, 0, 0, 0, 0, 0, 0]

/-- The common denominator of `cert7_4`. -/
def cert7_4Den : ℤ := 1

/-- The same certificate as rationals: `y 1 = 1`. Derived from the integer
form, so the two cannot drift apart. -/
def cert7_4 : ℕ → ℚ := ratOfInt cert7_4Int cert7_4Den

-- 4 dual constraints, each a sum of 7 integer products
theorem intCheck_cert7_4 : intCheck 7 4 cert7_4Int cert7_4Den = true := by decide

theorem dualCert_cert7_4 : DualCert 7 2 4 cert7_4 :=
  dualCert_of_intCheck intCheck_cert7_4

theorem A_7_2_4_le : A 7 2 4 ≤ 8 :=
  A_le_of_intCert (p := cert7_4Int) (D := cert7_4Den) (by norm_num) intCheck_cert7_4
    (by decide)



/-- Certificate for `n = 11`, `d = 5`, scaled by its common denominator
`5`. Index `0` is unused. -/
def cert11_5Int : List ℤ :=
  [0, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 5]

/-- The common denominator of `cert11_5`. -/
def cert11_5Den : ℤ := 5

/-- The same certificate as rationals: `y 1 = 1`, `y 2 = 1/5`, `y 11 = 1`. Derived from the integer
form, so the two cannot drift apart. -/
def cert11_5 : ℕ → ℚ := ratOfInt cert11_5Int cert11_5Den

-- 7 dual constraints, each a sum of 11 integer products
theorem intCheck_cert11_5 : intCheck 11 5 cert11_5Int cert11_5Den = true := by decide

theorem dualCert_cert11_5 : DualCert 11 2 5 cert11_5 :=
  dualCert_of_intCheck intCheck_cert11_5

theorem A_11_2_5_le : A 11 2 5 ≤ 24 :=
  A_le_of_intCert (p := cert11_5Int) (D := cert11_5Den) (by norm_num) intCheck_cert11_5
    (by decide)



/-- Certificate for `n = 13`, `d = 3`, scaled by its common denominator
`12`. Index `0` is unused. -/
def cert13_3Int : List ℤ :=
  [0, 9, 6, 4, 2, 1, 0, 0, 0, 1, 2, 4, 6, 9]

/-- The common denominator of `cert13_3`. -/
def cert13_3Den : ℤ := 12

/-- The same certificate as rationals: `y 1 = 3/4`, `y 2 = 1/2`, `y 3 = 1/3`, `y 4 = 1/6`, `y 5
= 1/12`, `y 9 = 1/12`, `y 10 = 1/6`, `y 11 = 1/3`, `y 12 = 1/2`, `y 13 = 3/4`. Derived from the
integer
form, so the two cannot drift apart. -/
def cert13_3 : ℕ → ℚ := ratOfInt cert13_3Int cert13_3Den

-- 11 dual constraints, each a sum of 13 integer products
theorem intCheck_cert13_3 : intCheck 13 3 cert13_3Int cert13_3Den = true := by decide

theorem dualCert_cert13_3 : DualCert 13 2 3 cert13_3 :=
  dualCert_of_intCheck intCheck_cert13_3

theorem A_13_2_3_le : A 13 2 3 ≤ 512 :=
  A_le_of_intCert (p := cert13_3Int) (D := cert13_3Den) (by norm_num) intCheck_cert13_3
    (by decide)



/-- Certificate for `n = 15`, `d = 5`, scaled by its common denominator
`35`. Index `0` is unused. -/
def cert15_5Int : List ℤ :=
  [0, 35, 11, 7, 2, 0, 0, 0, 0, 0, 0, 0, 1, 7, 7, 35]

/-- The common denominator of `cert15_5`. -/
def cert15_5Den : ℤ := 35

/-- The same certificate as rationals: `y 1 = 1`, `y 2 = 11/35`, `y 3 = 1/5`, `y 4 = 2/35`, `y
12 = 1/35`, `y 13 = 1/5`, `y 14 = 1/5`, `y 15 = 1`. Derived from the integer
form, so the two cannot drift apart. -/
def cert15_5 : ℕ → ℚ := ratOfInt cert15_5Int cert15_5Den

-- 11 dual constraints, each a sum of 15 integer products
theorem intCheck_cert15_5 : intCheck 15 5 cert15_5Int cert15_5Den = true := by decide

theorem dualCert_cert15_5 : DualCert 15 2 5 cert15_5 :=
  dualCert_of_intCheck intCheck_cert15_5

theorem A_15_2_5_le : A 15 2 5 ≤ 256 :=
  A_le_of_intCert (p := cert15_5Int) (D := cert15_5Den) (by norm_num) intCheck_cert15_5
    (by decide)
-- The `#`-command linter is off here on purpose: these commands are the replay.
set_option linter.hashCommand false

#guard dualCheck 7 2 4 cert7_4
#guard bound 7 2 cert7_4 == 8
#guard dualCheck 11 2 5 cert11_5
#guard bound 11 2 cert11_5 == 24
#guard dualCheck 13 2 3 cert13_3
#guard bound 13 2 cert13_3 == 512
#guard dualCheck 15 2 5 cert15_5
#guard bound 15 2 cert15_5 == 256

end Delsarte.Certificate
