/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Delsarte.Certificate.Verify

/-!
# Certified bounds, part 3 of 3: `A(6,2,3)`, `A(10,2,5)`, `A(12,2,5)`, `A(15,2,6)`

One third of the table described in `Delsarte/Certificate/Table.lean`. The split
is not cosmetic: these three modules import only the verifier, so Lake elaborates
them in parallel. Exact rational arithmetic is what this repository costs, and
`Delsarte.Certificate.Table` alone was 40 s of a 82 s build.

Generated by `delsarte_lp.emit_lean`; see `Delsarte/Certificate/Table.lean` for
why these declarations are generated rather than typed.
-/

namespace Delsarte.Certificate

open Delsarte

/-- Certificate for `n = 6`, `d = 3`; the linear program's optimum. -/
def cert6_3 : ℕ → ℚ
  | 1 => 1
  | 6 => 1
  | _ => 0

set_option maxHeartbeats 800000 in
-- 4 dual constraints, each a sum of 6 Krawtchouk values
theorem dualCert_cert6_3 : DualCert 6 2 3 cert6_3 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert6_3]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 6 2 _ _ (by norm_num)] <;>
      norm_num [cert6_3, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 800000 in
-- the same unfolding, at i = 0
theorem bound_cert6_3 : bound 6 2 cert6_3 = 8 := by
  rw [bound_eq_rec]
  norm_num [cert6_3, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_6_2_3_le : A 6 2 3 ≤ 8 :=
  A_le_of_dualCert (by norm_num) dualCert_cert6_3 (by rw [bound_cert6_3]; norm_num)



/-- Certificate for `n = 10`, `d = 5`; the linear program's optimum. -/
def cert10_5 : ℕ → ℚ
  | 1 => 1
  | 10 => 1
  | _ => 0

set_option maxHeartbeats 800000 in
-- 6 dual constraints, each a sum of 10 Krawtchouk values
theorem dualCert_cert10_5 : DualCert 10 2 5 cert10_5 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert10_5]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 10 2 _ _ (by norm_num)] <;>
      norm_num [cert10_5, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 800000 in
-- the same unfolding, at i = 0
theorem bound_cert10_5 : bound 10 2 cert10_5 = 12 := by
  rw [bound_eq_rec]
  norm_num [cert10_5, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_10_2_5_le : A 10 2 5 ≤ 12 :=
  A_le_of_dualCert (by norm_num) dualCert_cert10_5 (by rw [bound_cert10_5]; norm_num)



/-- Certificate for `n = 12`, `d = 5`; the linear program's optimum. -/
def cert12_5 : ℕ → ℚ
  | 1 => 2/3
  | 2 => 7/27
  | 3 => 1/18
  | 11 => 5/54
  | 12 => 5/9
  | _ => 0

set_option maxHeartbeats 1200000 in
-- 8 dual constraints, each a sum of 12 Krawtchouk values
theorem dualCert_cert12_5 : DualCert 12 2 5 cert12_5 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert12_5]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 12 2 _ _ (by norm_num)] <;>
      norm_num [cert12_5, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 1200000 in
-- the same unfolding, at i = 0
theorem bound_cert12_5 : bound 12 2 cert12_5 = 40 := by
  rw [bound_eq_rec]
  norm_num [cert12_5, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_12_2_5_le : A 12 2 5 ≤ 40 :=
  A_le_of_dualCert (by norm_num) dualCert_cert12_5 (by rw [bound_cert12_5]; norm_num)



/-- Certificate for `n = 15`, `d = 6`; the linear program's optimum. -/
def cert15_6 : ℕ → ℚ
  | 1 => 1
  | 2 => 1/5
  | 3 => 3/17
  | 12 => 2/85
  | _ => 0

set_option maxHeartbeats 1200000 in
-- 10 dual constraints, each a sum of 15 Krawtchouk values
theorem dualCert_cert15_6 : DualCert 15 2 6 cert15_6 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert15_6]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 15 2 _ _ (by norm_num)] <;>
      norm_num [cert15_6, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 1200000 in
-- the same unfolding, at i = 0
theorem bound_cert15_6 : bound 15 2 cert15_6 = 128 := by
  rw [bound_eq_rec]
  norm_num [cert15_6, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_15_2_6_le : A 15 2 6 ≤ 128 :=
  A_le_of_dualCert (by norm_num) dualCert_cert15_6 (by rw [bound_cert15_6]; norm_num)



end Delsarte.Certificate
