/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Delsarte.Certificate.Integer

/-!
# Certified bounds, part 1 of 3: `A(8,2,4)`, `A(12,2,6)`, `A(14,2,5)`, `A(24,2,8)`

One third of the table described in `Delsarte/Certificate/Table.lean`. The split
is not cosmetic: these three modules import only the verifier, so Lake elaborates
them in parallel.

Each certificate is stored as integers scaled by its common denominator, and each
check is `decide`: the kernel reduces the whole thing in `ℤ`, see
`Delsarte/Certificate/Integer.lean`. The rational form is derived from the integer
one rather than transcribed, so the two cannot drift apart.

Generated by `delsarte_lp.emit_lean`; see `Delsarte/Certificate/Table.lean` for
why these declarations are generated rather than typed.
-/

namespace Delsarte.Certificate

open Delsarte

-- kernel reduction of the Krawtchouk table needs more than the default depth
set_option maxRecDepth 100000

/-- Certificate for `n = 8`, `d = 4`, scaled by its common denominator
`4`. Index `0` is unused. -/
def cert8_4Int : List ℤ :=
  [0, 4, 1, 0, 0, 0, 0, 0, 0]

/-- The common denominator of `cert8_4`. -/
def cert8_4Den : ℤ := 4

/-- The same certificate as rationals: `y 1 = 1`, `y 2 = 1/4`. Derived from the integer
form, so the two cannot drift apart. -/
def cert8_4 : ℕ → ℚ := ratOfInt cert8_4Int cert8_4Den

-- 5 dual constraints, each a sum of 8 integer products
theorem intCheck_cert8_4 : intCheck 8 4 cert8_4Int cert8_4Den = true := by decide

theorem dualCert_cert8_4 : DualCert 8 2 4 cert8_4 :=
  dualCert_of_intCheck intCheck_cert8_4

theorem A_8_2_4_le : A 8 2 4 ≤ 16 :=
  A_le_of_intCert (p := cert8_4Int) (D := cert8_4Den) (by norm_num) intCheck_cert8_4
    (by decide)



/-- Certificate for `n = 12`, `d = 6`, scaled by its common denominator
`6`. Index `0` is unused. -/
def cert12_6Int : List ℤ :=
  [0, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

/-- The common denominator of `cert12_6`. -/
def cert12_6Den : ℤ := 6

/-- The same certificate as rationals: `y 1 = 1`, `y 2 = 1/6`. Derived from the integer
form, so the two cannot drift apart. -/
def cert12_6 : ℕ → ℚ := ratOfInt cert12_6Int cert12_6Den

-- 7 dual constraints, each a sum of 12 integer products
theorem intCheck_cert12_6 : intCheck 12 6 cert12_6Int cert12_6Den = true := by decide

theorem dualCert_cert12_6 : DualCert 12 2 6 cert12_6 :=
  dualCert_of_intCheck intCheck_cert12_6

theorem A_12_2_6_le : A 12 2 6 ≤ 24 :=
  A_le_of_intCert (p := cert12_6Int) (D := cert12_6Den) (by norm_num) intCheck_cert12_6
    (by decide)



/-- Certificate for `n = 14`, `d = 5`, scaled by its common denominator
`5`. Index `0` is unused. -/
def cert14_5Int : List ℤ :=
  [0, 5, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 5]

/-- The common denominator of `cert14_5`. -/
def cert14_5Den : ℤ := 5

/-- The same certificate as rationals: `y 1 = 1`, `y 2 = 1/5`, `y 3 = 1/5`, `y 12 = 1/5`, `y 13
= 1/5`, `y 14 = 1`. Derived from the integer
form, so the two cannot drift apart. -/
def cert14_5 : ℕ → ℚ := ratOfInt cert14_5Int cert14_5Den

-- 10 dual constraints, each a sum of 14 integer products
theorem intCheck_cert14_5 : intCheck 14 5 cert14_5Int cert14_5Den = true := by decide

theorem dualCert_cert14_5 : DualCert 14 2 5 cert14_5 :=
  dualCert_of_intCheck intCheck_cert14_5

theorem A_14_2_5_le : A 14 2 5 ≤ 128 :=
  A_le_of_intCert (p := cert14_5Int) (D := cert14_5Den) (by norm_num) intCheck_cert14_5
    (by decide)



/-- Certificate for `n = 24`, `d = 8`, scaled by its common denominator
`70803936`. Index `0` is unused. -/
def cert24_8Int : List ℤ :=
  [0, 70803936, 39894981, 17491992, 5865620, 1516624, 209571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   141639, 824776, 2188796, 4142544, 3865785, 0, 0]

/-- The common denominator of `cert24_8`. -/
def cert24_8Den : ℤ := 70803936

/-- The same certificate as rationals: `y 1 = 1`, `y 2 = 1899761/3371616`, `y 3 =
104119/421452`, `y 4 = 1466405/17700984`, `y 5 = 94789/4425246`, `y 6 = 69857/23601312`, `y 18
= 47213/23601312`, `y 19 = 103097/8850492`, `y 20 = 547199/17700984`, `y 21 = 12329/210726`, `y
22 = 184085/3371616`. Derived from the integer
form, so the two cannot drift apart. -/
def cert24_8 : ℕ → ℚ := ratOfInt cert24_8Int cert24_8Den

-- 17 dual constraints, each a sum of 24 integer products
theorem intCheck_cert24_8 : intCheck 24 8 cert24_8Int cert24_8Den = true := by decide

theorem dualCert_cert24_8 : DualCert 24 2 8 cert24_8 :=
  dualCert_of_intCheck intCheck_cert24_8

theorem A_24_2_8_le : A 24 2 8 ≤ 4096 :=
  A_le_of_intCert (p := cert24_8Int) (D := cert24_8Den) (by norm_num) intCheck_cert24_8
    (by decide)

-- The `#`-command linter is off here on purpose: these commands are the replay.
set_option linter.hashCommand false

#guard dualCheck 8 2 4 cert8_4
#guard bound 8 2 cert8_4 == 16
#guard dualCheck 12 2 6 cert12_6
#guard bound 12 2 cert12_6 == 24
#guard dualCheck 14 2 5 cert14_5
#guard bound 14 2 cert14_5 == 128
#guard dualCheck 24 2 8 cert24_8
#guard bound 24 2 cert24_8 == 4096

end Delsarte.Certificate
