/-
Copyright (c) 2026 Jean-Charles Gouleau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Charles Gouleau
-/
import Delsarte.Certificate.Verify

/-!
# Certified bounds, part 2 of 3: `A(7,2,4)`, `A(11,2,5)`, `A(13,2,3)`, `A(15,2,5)`

One third of the table described in `Delsarte/Certificate/Table.lean`. The split
is not cosmetic: these three modules import only the verifier, so Lake elaborates
them in parallel. Exact rational arithmetic is what this repository costs, and
`Delsarte.Certificate.Table` alone was 40 s of a 82 s build.

Generated by `delsarte_lp.emit_lean`; see `Delsarte/Certificate/Table.lean` for
why these declarations are generated rather than typed.
-/

namespace Delsarte.Certificate

open Delsarte

/-- Certificate for `n = 7`, `d = 4`; the linear program's optimum. -/
def cert7_4 : ℕ → ℚ
  | 1 => 1
  | _ => 0

set_option maxHeartbeats 800000 in
-- 4 dual constraints, each a sum of 7 Krawtchouk values
theorem dualCert_cert7_4 : DualCert 7 2 4 cert7_4 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert7_4]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 7 2 _ _ (by norm_num)] <;>
      norm_num [cert7_4, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 800000 in
-- the same unfolding, at i = 0
theorem bound_cert7_4 : bound 7 2 cert7_4 = 8 := by
  rw [bound_eq_rec]
  norm_num [cert7_4, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_7_2_4_le : A 7 2 4 ≤ 8 :=
  A_le_of_dualCert (by norm_num) dualCert_cert7_4 (by rw [bound_cert7_4]; norm_num)



/-- Certificate for `n = 11`, `d = 5`; the linear program's optimum. -/
def cert11_5 : ℕ → ℚ
  | 1 => 1
  | 2 => 1/5
  | 11 => 1
  | _ => 0

set_option maxHeartbeats 1200000 in
-- 7 dual constraints, each a sum of 11 Krawtchouk values
theorem dualCert_cert11_5 : DualCert 11 2 5 cert11_5 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert11_5]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 11 2 _ _ (by norm_num)] <;>
      norm_num [cert11_5, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 1200000 in
-- the same unfolding, at i = 0
theorem bound_cert11_5 : bound 11 2 cert11_5 = 24 := by
  rw [bound_eq_rec]
  norm_num [cert11_5, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_11_2_5_le : A 11 2 5 ≤ 24 :=
  A_le_of_dualCert (by norm_num) dualCert_cert11_5 (by rw [bound_cert11_5]; norm_num)



/-- Certificate for `n = 13`, `d = 3`; the linear program's optimum. -/
def cert13_3 : ℕ → ℚ
  | 1 => 3/4
  | 2 => 1/2
  | 3 => 1/3
  | 4 => 1/6
  | 5 => 1/12
  | 9 => 1/12
  | 10 => 1/6
  | 11 => 1/3
  | 12 => 1/2
  | 13 => 3/4
  | _ => 0

set_option maxHeartbeats 1200000 in
-- 11 dual constraints, each a sum of 13 Krawtchouk values
theorem dualCert_cert13_3 : DualCert 13 2 3 cert13_3 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert13_3]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 13 2 _ _ (by norm_num)] <;>
      norm_num [cert13_3, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 1200000 in
-- the same unfolding, at i = 0
theorem bound_cert13_3 : bound 13 2 cert13_3 = 512 := by
  rw [bound_eq_rec]
  norm_num [cert13_3, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_13_2_3_le : A 13 2 3 ≤ 512 :=
  A_le_of_dualCert (by norm_num) dualCert_cert13_3 (by rw [bound_cert13_3]; norm_num)



/-- Certificate for `n = 15`, `d = 5`; the linear program's optimum. -/
def cert15_5 : ℕ → ℚ
  | 1 => 1
  | 2 => 11/35
  | 3 => 1/5
  | 4 => 2/35
  | 12 => 1/35
  | 13 => 1/5
  | 14 => 1/5
  | 15 => 1
  | _ => 0

set_option maxHeartbeats 1200000 in
-- 11 dual constraints, each a sum of 15 Krawtchouk values
theorem dualCert_cert15_5 : DualCert 15 2 5 cert15_5 := by
  constructor
  · intro k hk; fin_cases hk <;> norm_num [cert15_5]
  · intro i hi
    fin_cases hi <;>
      rw [dualSlack_eq_rec 15 2 _ _ (by norm_num)] <;>
      norm_num [cert15_5, krawtchoukRec, Finset.sum_Icc_succ_top]

set_option maxHeartbeats 1200000 in
-- the same unfolding, at i = 0
theorem bound_cert15_5 : bound 15 2 cert15_5 = 256 := by
  rw [bound_eq_rec]
  norm_num [cert15_5, krawtchoukRec, Finset.sum_Icc_succ_top]

theorem A_15_2_5_le : A 15 2 5 ≤ 256 :=
  A_le_of_dualCert (by norm_num) dualCert_cert15_5 (by rw [bound_cert15_5]; norm_num)



end Delsarte.Certificate
