name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1
      - name: Check for sorry
        run: |
          ! grep -rn --include='*.lean' -E '\bsorry\b' Delsarte/
